// <auto-generated />
using System;
using BG.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BG.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BgDbContext))]
    [Migration("20260311194944_AddGuaranteeCategory")]
    partial class AddGuaranteeCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BG.Domain.Guarantees.Guarantee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GuaranteeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrincipalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupersededByGuaranteeNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteeNumber")
                        .IsUnique();

                    b.ToTable("guarantees", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeCorrespondence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedToGuaranteeAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("GuaranteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GuaranteeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateOnly>("LetterDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ScannedDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteeRequestId");

                    b.HasIndex("ScannedDocumentId");

                    b.HasIndex("GuaranteeId", "LetterDate");

                    b.ToTable("guarantee_correspondence", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("ExtractionMethod")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("GuaranteeId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntakeScenarioKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("VerifiedDataJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteeId", "CapturedAtUtc");

                    b.ToTable("guarantee_documents", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid?>("GuaranteeCorrespondenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuaranteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GuaranteeRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NewAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("NewExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PreviousAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("PreviousExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteeCorrespondenceId");

                    b.HasIndex("GuaranteeRequestId");

                    b.HasIndex("GuaranteeId", "OccurredAtUtc");

                    b.ToTable("guarantee_events", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletionCorrespondenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuaranteeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<decimal?>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("RequestedExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTimeOffset?>("SubmittedToBankAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteeId", "Status");

                    b.HasIndex("RequestedByUserId", "Status");

                    b.ToTable("guarantee_requests", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Identity.Permission", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoleId", "PermissionKey");

                    b.HasIndex("PermissionKey");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Operations.OperationsReviewItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuaranteeCorrespondenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuaranteeDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuaranteeId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuaranteeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RoutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutedToLaneKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ScenarioKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("GuaranteeCorrespondenceId");

                    b.HasIndex("GuaranteeDocumentId");

                    b.HasIndex("GuaranteeId", "Status");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.ToTable("operations_review_items", (string)null);
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeCorrespondence", b =>
                {
                    b.HasOne("BG.Domain.Guarantees.Guarantee", "Guarantee")
                        .WithMany("Correspondence")
                        .HasForeignKey("GuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG.Domain.Guarantees.GuaranteeRequest", "GuaranteeRequest")
                        .WithMany("Correspondence")
                        .HasForeignKey("GuaranteeRequestId");

                    b.HasOne("BG.Domain.Guarantees.GuaranteeDocument", "ScannedDocument")
                        .WithMany("Correspondence")
                        .HasForeignKey("ScannedDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guarantee");

                    b.Navigation("GuaranteeRequest");

                    b.Navigation("ScannedDocument");
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeDocument", b =>
                {
                    b.HasOne("BG.Domain.Guarantees.Guarantee", "Guarantee")
                        .WithMany("Documents")
                        .HasForeignKey("GuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarantee");
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeEvent", b =>
                {
                    b.HasOne("BG.Domain.Guarantees.GuaranteeCorrespondence", "GuaranteeCorrespondence")
                        .WithMany()
                        .HasForeignKey("GuaranteeCorrespondenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BG.Domain.Guarantees.Guarantee", "Guarantee")
                        .WithMany("Events")
                        .HasForeignKey("GuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG.Domain.Guarantees.GuaranteeRequest", "GuaranteeRequest")
                        .WithMany()
                        .HasForeignKey("GuaranteeRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guarantee");

                    b.Navigation("GuaranteeCorrespondence");

                    b.Navigation("GuaranteeRequest");
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeRequest", b =>
                {
                    b.HasOne("BG.Domain.Guarantees.Guarantee", "Guarantee")
                        .WithMany("Requests")
                        .HasForeignKey("GuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guarantee");
                });

            modelBuilder.Entity("BG.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("BG.Domain.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG.Domain.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BG.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("BG.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BG.Domain.Operations.OperationsReviewItem", b =>
                {
                    b.HasOne("BG.Domain.Guarantees.GuaranteeCorrespondence", "GuaranteeCorrespondence")
                        .WithMany()
                        .HasForeignKey("GuaranteeCorrespondenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BG.Domain.Guarantees.GuaranteeDocument", "GuaranteeDocument")
                        .WithMany()
                        .HasForeignKey("GuaranteeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BG.Domain.Guarantees.Guarantee", "Guarantee")
                        .WithMany()
                        .HasForeignKey("GuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guarantee");

                    b.Navigation("GuaranteeCorrespondence");

                    b.Navigation("GuaranteeDocument");
                });

            modelBuilder.Entity("BG.Domain.Guarantees.Guarantee", b =>
                {
                    b.Navigation("Correspondence");

                    b.Navigation("Documents");

                    b.Navigation("Events");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeDocument", b =>
                {
                    b.Navigation("Correspondence");
                });

            modelBuilder.Entity("BG.Domain.Guarantees.GuaranteeRequest", b =>
                {
                    b.Navigation("Correspondence");
                });

            modelBuilder.Entity("BG.Domain.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BG.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BG.Domain.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
