name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore BG.sln

      - name: Build
        run: dotnet build BG.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BG.sln --configuration Release --no-build
